with Coordonnee; use Coordonnee;
package body remplirGrille is

   ------------------------------
   -- grille du nouvel an 2018 --
   ------------------------------

   function grille1TresTresFacileDuNouvelAn2018 return Type_Grille is
      g : Type_Grille;
      c : Type_Coordonnee;
   begin
      -- remplissage grille
      g := construireGrille;
      -- ligne 1
      c := construireCoordonnees (1, 1);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (1, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 5);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (1, 6);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (1, 7);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (1, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 9);
      fixerChiffre (g, c, 0);
      -- ligne 2
      c := construireCoordonnees (2, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 2);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (2, 3);
      fixerChiffre (g, c, 9);
      c := construireCoordonnees (2, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 5);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (2, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 9);
      fixerChiffre (g, c, 3);
      -- ligne 3
      c := construireCoordonnees (3, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 3);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (3, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 6);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (3, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 8);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (3, 9);
      fixerChiffre (g, c, 7);
      -- ligne 4
      c := construireCoordonnees (4, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 3);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (4, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 5);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (4, 6);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (4, 7);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (4, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 9);
      fixerChiffre (g, c, 0);
      -- ligne 5
      c := construireCoordonnees (5, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 3);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (5, 4);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (5, 5);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (5, 6);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (5, 7);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (5, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 9);
      fixerChiffre (g, c, 0);
      -- ligne 6
      c := construireCoordonnees (6, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 3);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (6, 4);
      fixerChiffre (g, c, 9);
      c := construireCoordonnees (6, 5);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (6, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 7);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (6, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 9);
      fixerChiffre (g, c, 0);
      -- ligne 7
      c := construireCoordonnees (7, 1);
      fixerChiffre (g, c, 9);
      c := construireCoordonnees (7, 2);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (7, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 4);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (7, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 7);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (7, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 9);
      fixerChiffre (g, c, 0);
      -- ligne 8
      c := construireCoordonnees (8, 1);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (8, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 5);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (8, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 7);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (8, 8);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (8, 9);
      fixerChiffre (g, c, 0);
      -- ligne 9
      c := construireCoordonnees (9, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 3);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (9, 4);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (9, 5);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (9, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 9);
      fixerChiffre (g, c, 5);
      return (g);
   end grille1TresTresFacileDuNouvelAn2018;

   --------------------------
   -- grille2TresTresFacile --
   --------------------------

   function grille2TresTresFacile return Type_Grille is
      g : Type_Grille;
      c : Type_Coordonnee;
   begin
      -- remplissage grille
      g := construireGrille;
      -- ligne 1
      c := construireCoordonnees (1, 1);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (1, 2);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (1, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 4);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (1, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 9);
      fixerChiffre (g, c, 0);
      -- ligne 2
      c := construireCoordonnees (2, 1);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (2, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 4);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (2, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 6);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (2, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 9);
      fixerChiffre (g, c, 0);
      -- ligne 3
      c := construireCoordonnees (3, 1);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (3, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 4);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (3, 5);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (3, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 8);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (3, 9);
      fixerChiffre (g, c, 2);
      -- ligne 4
      c := construireCoordonnees (4, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 2);
      fixerChiffre (g, c, 9);
      c := construireCoordonnees (4, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 4);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (4, 5);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (4, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 7);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (4, 8);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (4, 9);
      fixerChiffre (g, c, 0);
      -- ligne 5
      c := construireCoordonnees (5, 1);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (5, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 3);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (5, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 5);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (5, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 7);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (5, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 9);
      fixerChiffre (g, c, 8);
      -- ligne 6
      c := construireCoordonnees (6, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 2);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (6, 3);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (6, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 5);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (6, 6);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (6, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 8);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (6, 9);
      fixerChiffre (g, c, 0);
      -- ligne 7
      c := construireCoordonnees (7, 1);
      fixerChiffre (g, c, 9);
      c := construireCoordonnees (7, 2);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (7, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 5);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (7, 6);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (7, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 9);
      fixerChiffre (g, c, 6);
      -- ligne 8
      c := construireCoordonnees (8, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 4);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (8, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 6);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (8, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 9);
      fixerChiffre (g, c, 7);
      -- ligne 9
      c := construireCoordonnees (9, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 6);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (9, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 8);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (9, 9);
      fixerChiffre (g, c, 1);
      return (g);
   end grille2TresTresFacile;

   -----------------------
   -- grille3TresFacile --
   -----------------------

   function grille3TresFacile return Type_Grille is
      g : Type_Grille;
      c : Type_Coordonnee;
   begin
      -- remplissage grille
      g := construireGrille;
      -- ligne 1
      c := construireCoordonnees (1, 1);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (1, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 7);
      fixerChiffre (g, c, 9);
      c := construireCoordonnees (1, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 9);
      fixerChiffre (g, c, 0);
      -- ligne 2
      c := construireCoordonnees (2, 1);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (2, 2);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (2, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 4);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (2, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 6);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (2, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 8);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (2, 9);
      fixerChiffre (g, c, 2);
      -- ligne 3
      c := construireCoordonnees (3, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 5);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (3, 6);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (3, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 8);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (3, 9);
      fixerChiffre (g, c,0);
      -- ligne 4
      c := construireCoordonnees (4, 1);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (4, 2);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (4, 3);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (4, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 6);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (4, 7);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (4, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 9);
      fixerChiffre (g, c, 0);
      -- ligne 5
      c := construireCoordonnees (5, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 3);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (5, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 5);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (5, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 7);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (5, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 9);
      fixerChiffre (g, c, 0);
      -- ligne 6
      c := construireCoordonnees (6, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 3);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (6, 4);
      fixerChiffre (g, c, 9);
      c := construireCoordonnees (6, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 7);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (6, 8);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (6, 9);
      fixerChiffre (g, c, 1);
      -- ligne 7
      c := construireCoordonnees (7, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 2);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (7, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 4);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (7, 5);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (7, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 9);
      fixerChiffre (g, c, 0);
      -- ligne 8
      c := construireCoordonnees (8, 1);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (8, 2);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (8, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 4);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (8, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 6);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (8, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 8);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (8, 9);
      fixerChiffre (g, c, 9);
      -- ligne 9
      c := construireCoordonnees (9, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 3);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (9, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 9);
      fixerChiffre (g, c, 5);
      return (g);
   end grille3TresFacile;

   -------------------
   -- grille4Facile --
   -------------------

   function grille4Facile return Type_Grille is
      g : Type_Grille;
      c : Type_Coordonnee;
   begin
      -- remplissage grille
      g := construireGrille;
      -- ligne 1
      c := construireCoordonnees (1, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 4);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (1, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 7);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (1, 8);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (1, 9);
      fixerChiffre (g, c, 9);
      -- ligne 2
      c := construireCoordonnees (2, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 3);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (2, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 9);
      fixerChiffre (g, c, 0);
      -- ligne 3
      c := construireCoordonnees (3, 1);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (3, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 3);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (3, 4);
      fixerChiffre (g, c, 9);
      c := construireCoordonnees (3, 5);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (3, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 8);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (3, 9);
      fixerChiffre (g, c,0);
      -- ligne 4
      c := construireCoordonnees (4, 1);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (4, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 8);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (4, 9);
      fixerChiffre (g, c, 1);
      -- ligne 5
      c := construireCoordonnees (5, 1);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (5, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 4);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (5, 5);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (5, 6);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (5, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 9);
      fixerChiffre (g, c, 3);
      -- ligne 6
      c := construireCoordonnees (6, 1);
      fixerChiffre (g, c, 9);
      c := construireCoordonnees (6, 2);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (6, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 9);
      fixerChiffre (g, c, 4);
      -- ligne 7
      c := construireCoordonnees (7, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 2);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (7, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 5);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (7, 6);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (7, 7);
      fixerChiffre (g, c, 9);
      c := construireCoordonnees (7, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 9);
      fixerChiffre (g, c, 5);
      -- ligne 8
      c := construireCoordonnees (8, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 7);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (8, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 9);
      fixerChiffre (g, c, 0);
      -- ligne 9
      c := construireCoordonnees (9, 1);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (9, 2);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (9, 3);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (9, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 6);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (9, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 9);
      fixerChiffre (g, c, 0);
      return (g);
   end grille4Facile;

   -------------------
   -- grille6Moyen --
   -------------------

   function grille6Moyen return Type_Grille is
      g : Type_Grille;
      c : Type_Coordonnee;
   begin
      -- remplissage grille
      g := construireGrille;
      -- ligne 1
      c := construireCoordonnees (1, 1);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (1, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 5);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (1, 6);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (1, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 9);
      fixerChiffre (g, c, 0);
      -- ligne 2
      c := construireCoordonnees (2, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 2);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (2, 3);
      fixerChiffre (g, c, 9);
      c := construireCoordonnees (2, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 9);
      fixerChiffre (g, c, 0);
      -- ligne 3
      c := construireCoordonnees (3, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 4);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (3, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 7);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (3, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 9);
      fixerChiffre (g, c, 8);
      -- ligne 4
      c := construireCoordonnees (4, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 9);
      fixerChiffre (g, c, 0);
      -- ligne 5
      c := construireCoordonnees (5, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 4);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (5, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 7);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (5, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 9);
      fixerChiffre (g, c, 0);
      -- ligne 6
      c := construireCoordonnees (6, 1);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (6, 2);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (6, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 6);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (6, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 8);
      fixerChiffre (g, c, 9);
      c := construireCoordonnees (6, 9);
      fixerChiffre (g, c, 7);
      -- ligne 7
      c := construireCoordonnees (7, 1);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (7, 2);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (7, 3);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (7, 4);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (7, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 9);
      fixerChiffre (g, c, 0);
      -- ligne 8
      c := construireCoordonnees (8, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 7);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (8, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 9);
      fixerChiffre (g, c, 0);
      -- ligne 9
      c := construireCoordonnees (9, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 3);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (9, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 5);
      fixerChiffre (g, c, 9);
      c := construireCoordonnees (9, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 7);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (9, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 9);
      fixerChiffre (g, c, 0);
      return (g);
   end grille6Moyen;

   -----------------------
   -- grille7Difficile --
   -----------------------

   function grille7Difficile return Type_Grille is
      g : Type_Grille;
      c : Type_Coordonnee;
   begin
      -- remplissage grille
      g := construireGrille;
      -- ligne 1
      c := construireCoordonnees (1, 1);
      fixerChiffre (g, c, 9);
      c := construireCoordonnees (1, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 5);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (1, 6);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (1, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 8);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (1, 9);
      fixerChiffre (g, c, 0);
      -- ligne 2
      c := construireCoordonnees (2, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 2);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (2, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 9);
      fixerChiffre (g, c, 5);
      -- ligne 3
      c := construireCoordonnees (3, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 2);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (3, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 7);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (3, 8);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (3, 9);
      fixerChiffre (g, c, 1);
      -- ligne 4
      c := construireCoordonnees (4, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 9);
      fixerChiffre (g, c, 0);
      -- ligne 5
      c := construireCoordonnees (5, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 4);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (5, 5);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (5, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 7);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (5, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 9);
      fixerChiffre (g, c, 0);
      -- ligne 6
      c := construireCoordonnees (6, 1);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (6, 2);
      fixerChiffre (g, c, 9);
      c := construireCoordonnees (6, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 6);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (6, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 8);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (6, 9);
      fixerChiffre (g, c, 0);
      -- ligne 7
      c := construireCoordonnees (7, 1);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (7, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 3);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (7, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 9);
      fixerChiffre (g, c, 0);
      -- ligne 8
      c := construireCoordonnees (8, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 3);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (8, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 5);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (8, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 7);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (8, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 9);
      fixerChiffre (g, c, 2);
      -- ligne 9
      c := construireCoordonnees (9, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 6);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (9, 7);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (9, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 9);
      fixerChiffre (g, c, 0);
      return (g);
   end grille7Difficile;
   ---------------------
   -- grille8Difficile --
   ---------------------

   function grille8Difficile return Type_Grille is
      g : Type_Grille;
      c : Type_Coordonnee;
   begin
      g := construireGrille;
      -- ligne 1
      c := construireCoordonnees (1, 1);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (1, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 6);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (1, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 9);
      fixerChiffre (g, c, 0);
      -- ligne 2
      c := construireCoordonnees (2, 1);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (2, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 3);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (2, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 9);
      fixerChiffre (g, c, 0);
      -- ligne 3
      c := construireCoordonnees (3, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 2);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (3, 3);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (3, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 7);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (3, 8);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (3, 9);
      fixerChiffre (g, c, 0);
      -- ligne 4
      c := construireCoordonnees (4, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 7);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (4, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 9);
      fixerChiffre (g, c, 6);
      -- ligne 5
      c := construireCoordonnees (5, 1);
      fixerChiffre (g, c, 9);
      c := construireCoordonnees (5, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 4);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (5, 5);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (5, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 7);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (5, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 9);
      fixerChiffre (g, c, 0);
      -- ligne 6
      c := construireCoordonnees (6, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 2);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (6, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 6);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (6, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 8);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (6, 9);
      fixerChiffre (g, c, 0);
      -- ligne 7
      c := construireCoordonnees (7, 1);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (7, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 9);
      fixerChiffre (g, c, 0);
      -- ligne 8
      c := construireCoordonnees (8, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 3);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (8, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 5);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (8, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 7);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (8, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 9);
      fixerChiffre (g, c, 5);
      -- ligne 9
      c := construireCoordonnees (9, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 5);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (9, 6);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (9, 7);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (9, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 9);
      fixerChiffre (g, c, 0);
      return (g);
   end grille8Difficile;

   -------------------------
   -- grille9TresDifficile --
   -------------------------

   function grille9TresDifficile return Type_Grille is
      g : Type_Grille;
      c : Type_Coordonnee;
   begin
      -- remplissage grille
      g := construireGrille;
      -- ligne 1
      c := construireCoordonnees (1, 1);
      fixerChiffre (g, c, 3);
      c := construireCoordonnees (1, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 5);
      fixerChiffre (g, c, 9);
      c := construireCoordonnees (1, 6);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (1, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (1, 8);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (1, 9);
      fixerChiffre (g, c, 0);
      -- ligne 2
      c := construireCoordonnees (2, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 4);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (2, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (2, 9);
      fixerChiffre (g, c, 0);
      -- ligne 3
      c := construireCoordonnees (3, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 3);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (3, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (3, 8);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (3, 9);
      fixerChiffre (g, c, 9);
      -- ligne 4
      c := construireCoordonnees (4, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 7);
      fixerChiffre (g, c, 1);
      c := construireCoordonnees (4, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (4, 9);
      fixerChiffre (g, c, 0);
      -- ligne 5
      c := construireCoordonnees (5, 1);
      fixerChiffre (g, c, 9);
      c := construireCoordonnees (5, 2);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (5, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 4);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (5, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 7);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (5, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (5, 9);
      fixerChiffre (g, c, 0);
      -- ligne 6
      c := construireCoordonnees (6, 1);
      fixerChiffre (g, c, 8);
      c := construireCoordonnees (6, 2);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (6, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 5);
      fixerChiffre (g, c, 5);
      c := construireCoordonnees (6, 6);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (6, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (6, 9);
      fixerChiffre (g, c, 3);
      -- ligne 7
      c := construireCoordonnees (7, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 5);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (7, 9);
      fixerChiffre (g, c, 0);
      -- ligne 8
      c := construireCoordonnees (8, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 3);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 5);
      fixerChiffre (g, c, 7);
      c := construireCoordonnees (8, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 7);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (8, 9);
      fixerChiffre (g, c, 2);
      -- ligne 9
      c := construireCoordonnees (9, 1);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 2);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 3);
      fixerChiffre (g, c, 2);
      c := construireCoordonnees (9, 4);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 5);
      fixerChiffre (g, c, 6);
      c := construireCoordonnees (9, 6);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 7);
      fixerChiffre (g, c, 4);
      c := construireCoordonnees (9, 8);
      fixerChiffre (g, c, 0);
      c := construireCoordonnees (9, 9);
      fixerChiffre (g, c, 0);
      return (g);
   end grille9TresDifficile;

end remplirGrille;
